name: Build Plugin

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          check-latest: true
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew clean build --no-daemon --refresh-dependencies

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: NoBreakCrops-jar
          path: build/libs/*.jar
